### ISSUE TITLE
2.9.1 HyperLogLogPlus does not count cardinality < 10000 at 14,32

### ISSUE THREAD

**Issue by kevandunsmore** [addthis/stream-lib#105]
Run this code:

>         HyperLogLogPlus hll = new HyperLogLogPlus(14, 32);
>         for (int i = 0; i < 10000; i++) {
>             UUID uuid = UUID.randomUUID();
>             hll.offer(uuid);
>         }
>         System.out.println("Cardinality = " + hll.cardinality());

In 2.9.0, the result is correct (9999 / 10000).

In 2.9.1, the result is 0.

It breaks at sp > 30

**Comment by kevandunsmore** [comment]
Looks like this is still broken in 2.9.2-SNAPSHOT

**Comment by kevandunsmore** [comment]
This commit broke it: e6aa33ac7d9ba47bd7c602cc0dc6f29115b33878

**Comment by kevandunsmore** [comment]
PR: https://github.com/addthis/stream-lib/pull/106

**Comment by yuesong** [comment]
Thanks for finding and fixing the bug!

**Comment by kevandunsmore** [comment]
No problem! 

Do you have a release date of 2.9.2 in mind? I'm using my local fork for our build internally - would be good to get back to the official version.

**Comment by yuesong** [comment]
Not yet, but will try to not let it sit too long.
