### ISSUE TITLE
CountMinSketch is not serializable

### ISSUE THREAD

**Issue by gokyo** [addthis/stream-lib#109]
Could we make _com.clearspring.analytics.stream.frequency.CountMinSketch_ implementing _java.io.Serializable_ please?

I am getting this error:
_org.apache.commons.lang3.SerializationException: java.io.NotSerializableException: com.clearspring.analytics.stream.frequency.CountMinSketch
at org.apache.commons.lang3.SerializationUtils.serialize(SerializationUtils.java:156)_

**Comment by abramsm** [comment]
CountMinSketch has `serialize` and `deserialize` in the current implementation.  It should be possible to extend the Serializable interface as well.  Have you looked to see if using the serialize/deserialize methods is viable for you?  Are you interested in submitting a pull request that makes the desired modification?

**Comment by gokyo** [comment]
Using `serialize` and `deserialize` would make my code complex.
Best for me would be to implement `Serializable` as it requires only a simple change on your code, and no changes on my code.
I can create a pull request if it is fine for you guys.
Thanks

**Comment by gokyo** [comment]
https://github.com/addthis/stream-lib/pull/110

**Comment by gokyo** [comment]
Hi
Any news on this ticket?
Thanks

**Comment by yuesong** [comment]
Sorry for the delay. The code looks fine. I'll do a final pass over.

**Comment by gokyo** [comment]
Thanks
Let me know when can be merged and released :+1:

**Comment by gokyo** [comment]
I close the issue as the code has been merged

**Comment by yuesong** [comment]
It's released.

**Comment by gokyo** [comment]
Thanks :+1:
