### ISSUE TITLE
CountMinSketch#size should be long everywhere in the code

### ISSUE THREAD

**Issue by gokyo** [addthis/stream-lib#111]
This code shows that the `CountMinSketch` `size()` method does not work as expected.
```
        double confidence = 0.999;
        double epsilon = 0.0001;
        int seed = 1;

        CountMinSketch sketch = new CountMinSketch(epsilon, confidence, seed);
        sketch.add(0, Integer.MAX_VALUE);
        long expectedSize = Integer.MAX_VALUE;
        Assert.assertEquals(expectedSize, sketch.size());

        CountMinSketch newSketch = CountMinSketch.merge(sketch, sketch);
        // bug: the next line is failing
        Assert.assertEquals(2 * expectedSize, newSketch.size());
```

There are two parts in the code where `size` is used wrongly as `int`:
https://github.com/addthis/stream-lib/blob/master/src/main/java/com/clearspring/analytics/stream/frequency/CountMinSketch.java#L68
https://github.com/addthis/stream-lib/blob/master/src/main/java/com/clearspring/analytics/stream/frequency/CountMinSketch.java#L186

It should be `long` everywhere.

Happy to fix it and add some unit tests creating a pull request.
Please let me know

**Comment by gokyo** [comment]
I updated the code that shows the bug (see above)

**Comment by gokyo** [comment]
Pull Request created here: https://github.com/addthis/stream-lib/pull/112
Let me know when you can merge and release the new code.
Thanks

**Comment by gokyo** [comment]
Any news not this? Maybe you are on holidays?!

**Comment by yuesong** [comment]
Thanks for the bug report and the pull request. It's indeed a holiday weekend here in the US. We will review this and get it out later this week.

**Comment by yuesong** [comment]
2.9.4 with #112 has been released and on its way to central.

**Comment by gokyo** [comment]
Great!

**Comment by gokyo** [comment]
I do not need it right now, but I forgot to include `ConservativeAddSketch` in the bug fix.
I have done it here: https://github.com/addthis/stream-lib/pull/113/
