### ISSUE TITLE
CountMinSketch#size goes to overflow

### ISSUE THREAD

**Issue by gokyo** [addthis/stream-lib#116]
This code (unit test) fails:
```
        CountMinSketch sketch = new CountMinSketch(0.0001, 0.99999, 1);
        sketch.add(3, Long.MAX_VALUE);
        long size1 = sketch.size();
        assertEquals(Long.MAX_VALUE, size1);

        sketch.add(4, 1);
        long size2 = sketch.size();
        assertTrue(size2 > size1);
```

I would check the `size` at construction and also after calling `#add()` or `#merge()`.
- the size must be always >= 0 (at construction but also at after any operation)
- the size after an operation such as `add` or `merge` must be bigger than the "previous size"
If the condition is not satisfy (because of the overflow), I would throw an exception.

Let me know if you agree. 
In case I could create a pull request with my solution.

**Comment by gokyo** [comment]
any news about this?

**Comment by abramsm** [comment]
Good catch.  

Since add currently allows size = 0 on the add method the check may be size must be >= previous size.

Thanks for offering to create the PR to resolve this.

**Comment by gokyo** [comment]
Thanks.
I have created a new pull request: https://github.com/addthis/stream-lib/pull/118
Let me know if everything looks good.
I also need a new tag/release.

**Comment by yuesong** [comment]
Thanks. PR merged.

**Comment by gokyo** [comment]
Thanks
Let me know when you plan to release a new version of the code

**Comment by yuesong** [comment]
v2.9.5 is on its way to central
