### ISSUE TITLE
A link in HyperLogLog.java is not accessible

### ISSUE THREAD

**Issue by canghai118** [addthis/stream-lib#123]
A link in HyperLogLog.java is not accessible at line 52

http://dsiutils.dsi.unimi.it/
https://github.com/addthis/stream-lib/blob/master/src/main/java/com/clearspring/analytics/stream/cardinality/HyperLogLog.java#L52
I want to know about how to deal with large number of counters
Can you place with a new link

**Comment by tedpearson** [comment]
Google Chrome suggested http://dsiutils.di.unimi.it/ as the link instead, which works. Does this look like the correct information?

**Comment by canghai118** [comment]
I'm not sure, but the link is accessible, thanks any way
