### ISSUE TITLE
how does  maxFalsePosProbability work

### ISSUE THREAD

**Issue by JanYunkai** [addthis/stream-lib#156]
i want set maxFalsePosProbability > 0.0000001 (part per million)
BloomFilter bloomFilter = new BloomFilter(sourceNumber, 0.0000001D);
but of not avail，does the maxFalsePosProbability have a min value？

this site https://hur.st/bloomfilter

in order to fix this problem, I made bigger numElements.
BloomFilter bloomFilter = new BloomFilter(sourceNumber * 3, 0.0000001D);

but bitset nbits is a Integer.
how to fix it?

**Comment by abramsm** [comment]
What error are you getting?  What are you trying to accomplish with such a
low max false positive rate?  At that point you may just consider a set or
some other deterministic data structure.

Matt

**Comment by JanYunkai** [comment]
thx
