### ISSUE TITLE
Deploy latest version to maven-central

### ISSUE THREAD

**Issue by ajtkulov** [addthis/stream-lib#160]
Please, could you deploy the latest version to maven-central?

I see the version from 2015, a bit outdated for me
https://mvnrepository.com/artifact/com.addthis/stream-lib/3.0.0

**Comment by tedpearson** [comment]
Hi @ajtkulov, The latest version is 2.9.8, with a different group id. Sorry for the confusion: https://repo1.maven.org/maven2/com/clearspring/analytics/stream/2.9.8

**Comment by ajtkulov** [comment]
sorry, my bad, I see it in readme now. I should spend a few seconds to read it carefully.
