### ISSUE TITLE
HyperLogLog incorrectly estimates very high cardinality values

### ISSUE THREAD

**Issue by abramsm** [addthis/stream-lib#7]
HyperLogLog uses a correction equation to estimate values > 1/30*2^32.  Unfortunately in java:

Math.pow(2,32) == Math.pow(-2,32) 

which is very sad.  This broke our implementation.  

While investigating the issue I also found that the long range correction actually hurts the precision of the estimate in some cases so I'm going to add an option to return the uncorrected value.

**Comment by foocomer7** [comment]
What do you mean by `unfortunately in Java`. Does this not hold true in other languages. @abramsm

**Comment by mako-taco** [comment]
I think there was a typo-- `(-2)^32` should most definite equal `2^32 `
