### ISSUE TITLE
ConcurrentStreamSummary does not implement Space-Saving algorithm

### ISSUE THREAD

**Issue by robertclancy** [addthis/stream-lib#74]
The ConcurrentStreamSummary implementation does not appear to implement the Space-Saving algorithm. In particular it appears to try to keep track of the minimum value (and introduces a race condition in the process), and remove this if the capacity is reached.

Also there appears to be a bug where the counts of the previous minimum is added to the count of the element added. For example the result of the following:

``` java
        ConcurrentStreamSummary<String> vs = new ConcurrentStreamSummary<String>(3);
        String[] stream = {"X", "X", "Y", "Y", "Y", "Z", "Z", "Z", "B"};
        for (String i : stream) {
            vs.offer(i);
        }
        List<ScoredItem<String>> topK = vs.peekWithScores(3);
```

is the list of strings `{"B", "Y", "Z"}` (not `{"X", "Y", "Z"}`) as the score of "X" was added to that of "B" when it was removed.

**Comment by fzakaria** [comment]
is the concurrent stream summary explained in a paper somewhere ?
