### ISSUE TITLE
HyperLogLog returns negative cardinality()

### ISSUE THREAD

**Issue by chtlp** [addthis/stream-lib#92]
Hi, I am trying out `HyperLogLog` and this simple Groovy snippet is giving me negative `cardinality()` results (although the negation of the returned value is quite accurate)

```
HyperLogLog hll = new HyperLogLog(12)

for (long i=0; i<2e8; ++i) {
    hll.offer(i)
}
log.info("hll estimate of 1e8 elements {}", hll.cardinality())
```
outputs
```
13:58:22.914 [main] INFO  misc.HyperLogLogTest - hll estimate of 1e8 elements -208378698
```
Something wrong here? Let me know if you can't reproduce. I am using 'com.clearspring.analytics:stream:2.1.1' from maven.

**Comment by abramsm** [comment]
I was not able to repeat this failure.  Perhaps something to do with groovy?

@Test
public void testHighCardinality() {
    long start = System.currentTimeMillis();
    HyperLogLog hyperLogLog = new HyperLogLog(12);
    long size = 200_000_000;
    for (int i = 0; i < size; i++) {
        hyperLogLog.offer(TestICardinality.streamElement(i));
        if (i % 1_000_000 == 0) {
            System.err.println(i);
        }
    }
    System.out.println("time: " + (System.currentTimeMillis() - start));
    long estimate = hyperLogLog.cardinality();
    double err = Math.abs(estimate - size) / (double) size;
    System.out.println(err);
    assertTrue(err < .1);
}


Results:

time: 21497
Delta: 0.003187035


That said, I recommend using HyperLogLogPlus.  It is better than
HyperLogLog in most ways.

Matt

**Comment by chtlp** [comment]
Hi I just realized I was using a really old version of stream-lib (2.1.1). I switched to 2.9.0 and the problem went away. Thanks and closing this issue now.
